In [ ]:
# import numerical python
import numpy as np

# import the pandas
import pandas as pd

#import the seaborn
import seaborn as sns

## import the matplolib
import matplotlib.pyplot as plt

In [ ]:
# load the data
df_house_price = pd.read_csv('House_Price1.csv')

In [ ]:
df_house_price.head()

,price,resid_area,air_qual,room_num,age,distance,teachers,poor_prop,airport,n_hos_beds,n_hot_rooms,waterbody,rainfall,bus_ter,Sold
0,24.0,32.31,0.538,6.575,65.2,4.35,24.7,4.98,YES,5.480,11.1920,River,23,YES,0
1,21.6,37.07,0.469,6.421,78.9,4.99,22.2,9.14,NO,7.332,12.1728,Lake,42,YES,1
2,34.7,37.07,0.469,7.185,61.1,5.03,22.2,4.03,NO,7.394,101.1200,NaN,38,YES,0
3,33.4,32.18,0.458,6.998,45.8,6.21,21.3,2.94,YES,9.268,11.2672,Lake,45,YES,0
4,36.2,32.18,0.458,7.147,54.2,6.16,21.3,5.33,NO,8.824,11.2896,Lake,55,YES,0

In [ ]:
dictionary={
    'price':'Price',
    'resid_area':'Residential_Area',
    'air_qual':'Air_Quality',
    'room_num':'Room_Number',
    'age':'Age',
    'distance':'Distance',
    'teachers':'Teachers',
    'poor_prop':'Poor_Property',
    'airport':'Airport',
    'n_hos_beds':'N_Hospital_Beds',
    'n_hot_rooms':'N_Hotel_Rooms',
    'waterbody':'Waterbody',
    'rainfall':'Rainfall',
    'bus_ter':'Bus_Ter',
    'Sold':'Sold'
}

In [ ]:
# perform the rename action
df_house_price = df_house_price.rename(columns=dictionary)

In [ ]:
# Do the authentic check
df_house_price.columns

Index(['Price', 'Residential_Area', 'Air_Quality', 'Room_Number', 'Age',
       'Distance', 'Teachers', 'Poor_Property', 'Airport', 'N_Hospital_Beds',
       'N_Hotel_Rooms', 'Waterbody', 'Rainfall', 'Bus_Ter', 'Sold'],
      dtype='object')

In [ ]:
### Null value Handling

In [ ]:
# lets treat the null values in waterbody column
df_house_price.Waterbody=df_house_price.Waterbody.fillna('River',inplace = True)

<ipython-input-14-731fc14cdc22>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_house_price.Waterbody=df_house_price.Waterbody.fillna('River',inplace = True)

In [ ]:
# store the target variable 'Chance of Admit' in a dataframe 'df_target'
df_target = df_house_price['Sold']

# store all the independent variables in a dataframe 'df_feature'
# drop the column 'Chance of Admit' using drop()
# 'axis = 1' drops the specified column
df_feature = df_house_price.drop('Sold', axis = 1)

In [ ]:
# Segregate the data based on the datatype
df_num = df_house_price.select_dtypes(include='number')
df_cat = df_house_price.select_dtypes(include='object')

In [ ]:
# Use Dummy encoding
df_encoded = pd.get_dummies(df_cat)
# Reset the index
df_encoded = df_encoded.reset_index()

In [ ]:
# import the standard scaler
from sklearn.preprocessing import StandardScaler

# initiate the standard scaler
ss = StandardScaler()

In [ ]:
# Scaled the value present in Numerical dataframe
scaled = ss.fit_transform(df_num)

In [ ]:
scaled

array([[ 0.16037616, -1.2879095 , -0.14421743, ..., -0.35339768,
        -1.29440816, -0.91287093],
       [-0.10125846, -0.59338101, -0.74026221, ..., -0.16599956,
         0.22543063,  1.09544512],
       [ 1.32683049, -0.59338101, -0.74026221, ..., 16.82883914,
        -0.09453543, -0.91287093],
       ...,
       [ 0.14947472,  0.11573841,  0.15812412, ..., -0.16248394,
        -0.65447604,  1.09544512],
       [-0.05765269,  0.11573841,  0.15812412, ...,  0.40781164,
         0.62538821,  1.09544512],
       [-0.38469596,  0.11573841,  0.15812412, ..., -0.55210694,
         0.46540518,  1.09544512]])

In [ ]:
# Numerate the data into the dataframe
scaled_df = pd.DataFrame(scaled,columns=df_num.columns)

In [ ]:
# Reset the Index
scaled_df = scaled_df.reset_index()

In [ ]:
# Show the data
scaled_df.head()

,index,Price,Residential_Area,Air_Quality,Room_Number,Age,Distance,Teachers,Poor_Property,N_Hospital_Beds,N_Hotel_Rooms,Rainfall,Sold
0,0,0.160376,-1.287909,-0.144217,0.413672,-0.120013,0.179451,1.459000,-1.075562,-1.640299,-0.353398,-1.294408,-0.912871
1,1,-0.101258,-0.593381,-0.740262,0.194274,0.367166,0.483280,0.303094,-0.492439,-0.384875,-0.166000,0.225431,1.095445
2,2,1.326830,-0.593381,-0.740262,1.282714,-0.265812,0.502269,0.303094,-1.208727,-0.342847,16.828839,-0.094535,-0.912871
3,3,1.185112,-1.306878,-0.835284,1.016303,-0.809889,1.062454,-0.113032,-1.361517,0.927490,-0.339029,0.465405,-0.912871
4,4,1.490352,-1.306878,-0.835284,1.228577,-0.511180,1.038717,-0.113032,-1.026501,0.626514,-0.334750,1.265320,-0.912871

In [ ]:
# concat encoded variable and scaled variable
df_independent = pd.concat([df_encoded,scaled_df],axis=1)

In [ ]:
# import the train test split
from sklearn.model_selection import train_test_split

In [ ]:
# split the data
x_train,x_test,y_train,y_test = train_test_split(df_independent,df_target,test_size=0.2)

**Decision Tree classifier**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

# create a decision tree classifer
tree_model = DecisionTreeClassifier()

# fit the model to the training data
tree_model.fit( x_train,y_train)

# predict on the testing data
predictions=tree_model.predict(x_test)

# calculate the classification report
class_report=classification_report(y_test,predictions)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      1.00      1.00        33

    accuracy                           1.00       102
   macro avg       1.00      1.00      1.00       102
weighted avg       1.00      1.00      1.00       102